package org.biopax.paxtools.model.level3;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Provenance OWL Class: sequenceLocationGroup
 *
 * @version generated on Fri Aug 17 19:19:30 GMT 2007
 */
public interface SequenceLocationGroup extends SequenceLocation
{


    // Property MEMBER-LOCATION


}
