/**
 * 
 */
package org.biopax.paxtools.util;

import java.util.Set;

import org.apache.lucene.document.Document;
import org.biopax.paxtools.controller.ModelUtils;
import org.biopax.paxtools.controller.ModelUtils.RelationshipType;
import org.biopax.paxtools.model.level3.RelationshipTypeVocabulary;
import org.biopax.paxtools.model.level3.RelationshipXref;
import org.biopax.paxtools.model.level3.Xref;
import org.hibernate.search.bridge.FieldBridge;
import org.hibernate.search.bridge.LuceneOptions;

/**
 * This is a tricky experimental search field bridge; it 
 * depends on special (generated by someone) rel.xrefs,
 * which 'id' property contains a pathway/interaction URI or name.
 * 
 * @author rodche
 */
public final class ProcessFieldBridge implements FieldBridge {

	@Override
	public void set(String name, Object value, Document document, LuceneOptions luceneOptions) {
		Set<RelationshipXref> refs 
			= new ClassFilterSet<Xref,RelationshipXref>((Set<Xref>) value, RelationshipXref.class);	
		for(RelationshipXref x : refs) {
			if(isProcessRelationshipXref(x))
				luceneOptions.addFieldToDocument(name, x.getId().toLowerCase(), document);
		}	
	}
	
	private boolean isProcessRelationshipXref(RelationshipXref rx) {
		RelationshipTypeVocabulary cv = rx.getRelationshipType();
		return cv != null && cv.getRDFId().equalsIgnoreCase(
			ModelUtils.relationshipTypeVocabularyUri(RelationshipType.PROCESS.name()));
	}
}
